### ISSUE TITLE
Codes for inference/evaluation

### ISSUE THREAD

**Issue by jihyukkim-nlp** [OpenMatch/COCO-DR#1]
Thank you for the interesting work!

I am wondering if codes for the inference/evaluation on BEIR datasets are available or planned to be shared.

I tried using [open-sourced BEIR evaluation codes](https://github.com/beir-cellar/beir#beers-quick-example) as follows.
I evaluated [COCO-DR (Base)](https://huggingface.co/OpenMatch/cocodr-base-msmarco) on SciFact dataset.
``` python
#### Download scifact.zip dataset and unzip the dataset
dataset = "scifact"
url = "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/{}.zip".format(dataset)
dataset_dir = 'experiments/datasets/beir/'
data_path = util.download_and_unzip(url, dataset_dir)
#### Provide the data_path where scifact has been downloaded and unzipped
corpus, queries, qrels = GenericDataLoader(data_folder=data_path).load(split="test")

#### Load the SBERT model and retrieve using cosine-similarity
model = DRES(models.SentenceBERT("OpenMatch/cocodr-base-msmarco"), batch_size=16)
retriever = EvaluateRetrieval(model, score_function="dot")
results = retriever.retrieve(corpus, queries)

#### Evaluate your model with NDCG@k, MAP@K, Recall@K and Precision@K  where k = [1,3,5,10,100,1000] 
ndcg, _map, recall, precision = retriever.evaluate(qrels, results, retriever.k_values)
```

But I got a lower performance than the reported performance in the [paper](https://arxiv.org/pdf/2210.15212.pdf): I got 0.254 nDCG@10 (reported number is 0.709).
```
2022-11-08 11:37:22 - NDCG@1: 0.1467
2022-11-08 11:37:22 - NDCG@3: 0.2189
2022-11-08 11:37:22 - NDCG@5: 0.2352
2022-11-08 11:37:22 - NDCG@10: 0.2535
2022-11-08 11:37:22 - NDCG@100: 0.3066
2022-11-08 11:37:22 - NDCG@1000: 0.3415
```

Best regards,
Jihyuk

**Comment by yueyu1030** [comment]
Hi Jihyuk,

Thanks for your interest! Yes, we plan to share the code for evaluation and will release it very soon (within this week). I will let you know once it is updated. 

Best,
Yue

**Comment by jihyukkim-nlp** [comment]
Hi Yue, 

Thank you for sharing!
BTW, I found that I was using mean pooling for the single vector representation. I replaced this with CLS pooling, and successfully reproduced the reported performance 😅 .

Thanks, 
Jihyuk

**Comment by yueyu1030** [comment]
Glad to know that : )  (Will still update the evaluation code for sure!)

**Comment by yueyu1030** [comment]
Hi Jihyuk,

We have updated our codes/scripts for evaluating BEIR tasks. Feel free to use it!

Best,
Yue
