### ISSUE TITLE
Questions about the results in Table 7 in the paper

### ISSUE THREAD

**Issue by JamesCao2048** [OpenMatch/COCO-DR#2]
Hi, I am very interested in your work and have some small questions.
As the results in Table 7 in the paper are not explained too much, I want to know is the metric MRR?
And did you evaluate the results at CodeSearchNet evaluation dataset with 99 queries?
By the way, is there any way to reproduce the results in Table 7 with the code in this repo?

Thanks a lot!

**Comment by yueyu1030** [comment]
Hi there,

I suppose you are talking about the table with the title `Comparison between iDRO and GroupDRO`. 

The metric in this table is nDCG@10, which is used for all BEIR tasks. In this work, we mainly evaluate our model on BEIR tasks and have not evaluated COCO-DR on other tasks. 

For table 7, please see the `ANCE` folder (https://github.com/OpenMatch/COCO-DR/tree/main/ANCE#step-3-training-with-mined-hard-negative-and-idro) and set the `dro_type` to `dro-greedy`.  Hope these explanations will be helpful.

Best,
Yue
