### ISSUE TITLE
Cannot find Command folder for ACNE

### ISSUE THREAD

**Issue by ekvall93** [OpenMatch/COCO-DR#3]
Hello, 

I find this project very interesting. 

I cannot see any folder for commands/install.sh and commands/run_ance.sh

Could you please upload these files?

Best regards,
Markus

**Comment by yueyu1030** [comment]
Hi Markus,

Thanks for your interest!  For the installation, we recommend using the installation procedure at https://github.com/microsoft/ANCE. For the run_ance part, our commands are in https://github.com/OpenMatch/COCO-DR/tree/main/ANCE#step-3-training-with-mined-hard-negative-and-idro. Let me know if you have other questions.

Best,
Yue
